maria-data:
    image: busybox:latest
    volumes:
        - ./Docker/data/mysql:/var/lib/mysql
maria:
    image: mariadb:latest
    ports:
        - "3306:3306"
    environment:
        - "MYSQL_ROOT_PASSWORD=root"
        - "MYSQL_USER=user"
        - "MYSQL_PASSWORD=user"
        - "MYSQL_DATABASE=symfony"
    volumes_from:
        - maria-data
mongo-data:
    image: busybox:latest
    volumes:
        - ./Docker/data/mongo:/data/db
mongo:
    image: mongo:latest
    ports:
        - "27017:27017"
    volumes_from:
        - mongo-data
code:
    image: busybox
    volumes:
        - ./blog:/var/www/
php:
    build: ./Docker/php/
    dockerfile: Dockerfile
    ports:
        - "9000:9000"
    working_dir: "/home/docker"
    volumes:
        - ./Docker/php/php.ini:/usr/local/etc/php/php.ini
    volumes_from:
        - code
    links:
        - "maria:maria"
        - "mongo:mongo"
nginx:
    image: nginx:latest
    ports:
        - "81:80"
    links:
        - "maria:maria"
        - "mongo:mongo"
        - "php:php"
    volumes_from:
        - code
    volumes:
        - ./Docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
